### ISSUE TITLE
PHP 8.4: Implicitly nullable parameter declarations deprecated

### ISSUE THREAD

**Issue by isg89** [waterholeforum/core#84]
### Bug description

On PHP version 8.4.8, I'm getting the following error in the console/terminal whenever I try to run `php artisan serve`. 

```
PHP Deprecated:  Waterhole\return_field(): Implicitly marking parameter $default as nullable is deprecated, the explicit nullable type must be used instead in /vendor/waterhole/core/src/helpers.php on line 113
```

PHP 8.4 introduced the deprecation of implicit nullable parameter declarations.

### Steps to reproduce

Update to PHP version 8.4.

### Logs

```shell

```

### Environment

```yaml
Laravel Version: 12.19.3  
PHP Version: 8.4.8  
Composer Version: 2.8.9  
Environment: local  
Debug Mode: ENABLED  
URL: localhost:8000  
Maintenance Mode: OFF  
Timezone: UTC  
Locale: en  
Waterhole Version: 0.4.12
```
